// SF Symbols to lucide-react map. Every component imports from here, so
// swapping the icon set or remapping a single symbol stays a one-file edit.
// Names mirror SF Symbol identifiers used in the macOS app (snake to camel).

import {
  Terminal,
  TextCursorInput,
  Lightbulb,
  Search,
  Plus,
  GripVertical,
  X,
  FolderClosed,
  FolderOpen,
  File,
  List,
  SquareSplitVertical,
  SquareSplitHorizontal,
  SquarePlus,
  CircleStop,
  CircleCheck,
  CircleX,
  RefreshCw,
  RotateCcw,
  Trash2,
  CircleArrowDown,
  Sparkles,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Copy,
  CornerDownRight,
  LayoutDashboard,
  MonitorCog,
  Sun,
  Moon,
  Send,
  Square,
  Save,
  ArrowRight,
  Settings as SettingsCog,
  Eye,
  Loader2,
  Check,
  Minus,
  Mic,
  Cpu,
} from "lucide-react";

export const Icons = {
  terminal: Terminal,
  textCursor: TextCursorInput,
  lightbulb: Lightbulb,
  search: Search,
  plus: Plus,
  gridDrag: GripVertical,
  close: X,
  folderFill: FolderClosed,
  folderOpen: FolderOpen,
  file: File,
  listBulletRect: List,
  splitVertical: SquareSplitVertical,
  splitHorizontal: SquareSplitHorizontal,
  addPane: SquarePlus,
  stopCircle: CircleStop,
  checkCircle: CircleCheck,
  failedCircle: CircleX,
  refresh: RefreshCw,
  rerunReverse: RotateCcw,
  trash: Trash2,
  updateAvailable: CircleArrowDown,
  updateApplying: RefreshCw,
  sparkles: Sparkles,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  copy: Copy,
  rerun: CornerDownRight,
  emptyDeck: LayoutDashboard,
  appearanceSystem: MonitorCog,
  appearanceLight: Sun,
  appearanceDark: Moon,
  send: Send,
  cancel: Square,
  save: Save,
  go: ArrowRight,
  settings: SettingsCog,
  eye: Eye,
  spinner: Loader2,
  check: Check,
  minimize: Minus,
  mic: Mic,
  cpu: Cpu,
} as const;

export type IconName = keyof typeof Icons;
